version: 0.2
env:
  variables:
    PNPM_HOME: "~/.local/pnpm"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - npm install --silent -g pnpm@8.6.0
      - pnpm install --frozen-lockfile --prod
      - export PATH="$PWD/node_modules/.bin:$PATH"
      - org-formation -v
      - pip install cfn-lint
  build:
    commands:
      - pnpm run print-tasks
      - pnpm run validate-tasks
      - pnpm run cfn-lint
