AWSTemplateFormatVersion: "2010-09-09-OC"

Parameters:
  targetIds:
    Type: CommaDelimitedList

Resources:
  AiOptOutPolicy:
    Type: AWS::Organizations::Policy
    Properties:
      Content: !ReadFile ./resources/ai-training-optout-policy.json
      Description: Opts out of sharing data for AI training purposes
      Name: GlobalAiOptOut
      Type: AISERVICES_OPT_OUT_POLICY
      TargetIds: !Ref targetIds
