AWSTemplateFormatVersion: "2010-09-09-OC"
Description: Default organization blueprint

# https://aws.amazon.com/blogs/mt/best-practices-for-organizational-units-with-aws-organizations/
Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      Alias: "{{organization-name}}-management"
      RootEmail: "{{management-root-email-address}}"
      AccountName: Management Account
      AccountId: "{{management-account-id}}"
      Tags:
        budget-alarm-threshold: 200
        budget-alarm-threshold-email-recipient: "{{budget-alarm-email-address}}"
        new-account-email-recipient: "{{new-account-alarm-email-address}}"

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      DefaultBuildAccessRoleName: OrganizationFormationBuildAccessRole

  # Production services
  WorkloadOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: workload
      Accounts: []

  # Organizational Unit used for shared networking
  InfrastructureOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: infrastructure
      Accounts: []

  # Organizational Unit used for the Software Development Life Cycle or CI/CD
  DeploymentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: deployment
      Accounts: []

  # Organizational Unit used for security accounts
  SecurityOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: security
      Accounts:
        - !Ref OrgBuildAccount
        - !Ref LogArchiveAccount

  OrgBuildAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: "{{organization-name}}-org-build"
      AccountName: Organization Build Account
      RootEmail: "{{org-build-root-email-address}}"
      Tags:
        budget-alarm-threshold: 50
        budget-alarm-threshold-email-recipient: "{{budget-alarm-email-address}}"
        new-account-email-recipient: "{{new-account-alarm-email-address}}"

  LogArchiveAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: "{{organization-name}}-log-archive"
      AccountName: Log Archive Account
      RootEmail: "{{log-archive-root-email-address}}"
      Tags:
        budget-alarm-threshold: 50
        budget-alarm-threshold-email-recipient: "{{budget-alarm-email-address}}"

  # Organizational Unit that contains accounts to be deleted from organization
  SuspendedOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: suspended
      Accounts: []
